# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/dialog_newGame.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 516)
        self.scrollArea_newGame = QtWidgets.QScrollArea(Dialog)
        self.scrollArea_newGame.setGeometry(QtCore.QRect(0, 0, 401, 651))
        self.scrollArea_newGame.setWidgetResizable(True)
        self.scrollArea_newGame.setObjectName("scrollArea_newGame")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 399, 649))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.buttonBox_newGame = QtWidgets.QDialogButtonBox(self.scrollAreaWidgetContents)
        self.buttonBox_newGame.setGeometry(QtCore.QRect(20, 450, 361, 32))
        self.buttonBox_newGame.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox_newGame.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox_newGame.setObjectName("buttonBox_newGame")
        self.formLayoutWidget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.formLayoutWidget.setGeometry(QtCore.QRect(20, 20, 361, 411))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_TotalAttempts = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_TotalAttempts.setObjectName("label_TotalAttempts")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_TotalAttempts)
        self.spinBox_TotalAttempts = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.spinBox_TotalAttempts.setObjectName("spinBox_TotalAttempts")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.spinBox_TotalAttempts)
        self.label_SuccessfulAttempts = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_SuccessfulAttempts.setObjectName("label_SuccessfulAttempts")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_SuccessfulAttempts)
        self.spinBox_SuccessfulAttempts = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.spinBox_SuccessfulAttempts.setObjectName("spinBox_SuccessfulAttempts")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.spinBox_SuccessfulAttempts)
        self.label_Attempt01 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_Attempt01.setObjectName("label_Attempt01")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_Attempt01)
        self.comboBox_Attempt01 = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox_Attempt01.setObjectName("comboBox_Attempt01")
        self.comboBox_Attempt01.addItem("")
        self.comboBox_Attempt01.addItem("")
        self.comboBox_Attempt01.addItem("")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.comboBox_Attempt01)
        self.label_Attempt02 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_Attempt02.setObjectName("label_Attempt02")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_Attempt02)
        self.comboBox_Attempt02 = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox_Attempt02.setObjectName("comboBox_Attempt02")
        self.comboBox_Attempt02.addItem("")
        self.comboBox_Attempt02.addItem("")
        self.comboBox_Attempt02.addItem("")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.comboBox_Attempt02)
        self.label_Attempt03 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_Attempt03.setObjectName("label_Attempt03")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_Attempt03)
        self.comboBox_Attempt03 = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox_Attempt03.setObjectName("comboBox_Attempt03")
        self.comboBox_Attempt03.addItem("")
        self.comboBox_Attempt03.addItem("")
        self.comboBox_Attempt03.addItem("")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.comboBox_Attempt03)
        self.label_Attempt04 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_Attempt04.setObjectName("label_Attempt04")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_Attempt04)
        self.comboBox_Attempt04 = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox_Attempt04.setObjectName("comboBox_Attempt04")
        self.comboBox_Attempt04.addItem("")
        self.comboBox_Attempt04.addItem("")
        self.comboBox_Attempt04.addItem("")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.comboBox_Attempt04)
        self.label_Attempt05 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_Attempt05.setObjectName("label_Attempt05")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_Attempt05)
        self.comboBox_Attempt05 = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox_Attempt05.setObjectName("comboBox_Attempt05")
        self.comboBox_Attempt05.addItem("")
        self.comboBox_Attempt05.addItem("")
        self.comboBox_Attempt05.addItem("")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.comboBox_Attempt05)
        self.label_Attempt06 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_Attempt06.setObjectName("label_Attempt06")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.label_Attempt06)
        self.comboBox_Attempt06 = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox_Attempt06.setObjectName("comboBox_Attempt06")
        self.comboBox_Attempt06.addItem("")
        self.comboBox_Attempt06.addItem("")
        self.comboBox_Attempt06.addItem("")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.comboBox_Attempt06)
        self.label_Attempt07 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_Attempt07.setObjectName("label_Attempt07")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.label_Attempt07)
        self.comboBox_Attempt07 = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox_Attempt07.setObjectName("comboBox_Attempt07")
        self.comboBox_Attempt07.addItem("")
        self.comboBox_Attempt07.addItem("")
        self.comboBox_Attempt07.addItem("")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.comboBox_Attempt07)
        self.label_Attempt08 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_Attempt08.setObjectName("label_Attempt08")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.LabelRole, self.label_Attempt08)
        self.comboBox_Attempt08 = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox_Attempt08.setObjectName("comboBox_Attempt08")
        self.comboBox_Attempt08.addItem("")
        self.comboBox_Attempt08.addItem("")
        self.comboBox_Attempt08.addItem("")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.FieldRole, self.comboBox_Attempt08)
        self.label_Attempt09 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_Attempt09.setObjectName("label_Attempt09")
        self.formLayout.setWidget(13, QtWidgets.QFormLayout.LabelRole, self.label_Attempt09)
        self.comboBox_Attempt09 = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox_Attempt09.setObjectName("comboBox_Attempt09")
        self.comboBox_Attempt09.addItem("")
        self.comboBox_Attempt09.addItem("")
        self.comboBox_Attempt09.addItem("")
        self.formLayout.setWidget(13, QtWidgets.QFormLayout.FieldRole, self.comboBox_Attempt09)
        self.label_Attempt10 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_Attempt10.setObjectName("label_Attempt10")
        self.formLayout.setWidget(14, QtWidgets.QFormLayout.LabelRole, self.label_Attempt10)
        self.comboBox_Attempt10 = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox_Attempt10.setObjectName("comboBox_Attempt10")
        self.comboBox_Attempt10.addItem("")
        self.comboBox_Attempt10.addItem("")
        self.comboBox_Attempt10.addItem("")
        self.formLayout.setWidget(14, QtWidgets.QFormLayout.FieldRole, self.comboBox_Attempt10)
        self.label_Attempt11 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_Attempt11.setWordWrap(True)
        self.label_Attempt11.setObjectName("label_Attempt11")
        self.formLayout.setWidget(15, QtWidgets.QFormLayout.LabelRole, self.label_Attempt11)
        self.comboBox_Attempt11 = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox_Attempt11.setObjectName("comboBox_Attempt11")
        self.comboBox_Attempt11.addItem("")
        self.comboBox_Attempt11.addItem("")
        self.comboBox_Attempt11.addItem("")
        self.formLayout.setWidget(15, QtWidgets.QFormLayout.FieldRole, self.comboBox_Attempt11)
        self.label_TotalAttempts_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_TotalAttempts_2.setObjectName("label_TotalAttempts_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_TotalAttempts_2)
        self.spinBox_TotalAttempts_2 = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.spinBox_TotalAttempts_2.setObjectName("spinBox_TotalAttempts_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.spinBox_TotalAttempts_2)
        self.label_SuccessfulAttempts_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_SuccessfulAttempts_2.setObjectName("label_SuccessfulAttempts_2")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_SuccessfulAttempts_2)
        self.spinBox_SuccessfulAttempts_2 = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.spinBox_SuccessfulAttempts_2.setObjectName("spinBox_SuccessfulAttempts_2")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.spinBox_SuccessfulAttempts_2)
        self.scrollArea_newGame.setWidget(self.scrollAreaWidgetContents)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_TotalAttempts.setText(_translate("Dialog", "Total Attempts:"))
        self.label_SuccessfulAttempts.setText(_translate("Dialog", "Successful Attempts:"))
        self.label_Attempt01.setText(_translate("Dialog", "Attempt #1:"))
        self.comboBox_Attempt01.setItemText(0, _translate("Dialog", "Unknown"))
        self.comboBox_Attempt01.setItemText(1, _translate("Dialog", "Successful"))
        self.comboBox_Attempt01.setItemText(2, _translate("Dialog", "Failed"))
        self.label_Attempt02.setText(_translate("Dialog", "Attempt # 2:"))
        self.comboBox_Attempt02.setItemText(0, _translate("Dialog", "Unknown"))
        self.comboBox_Attempt02.setItemText(1, _translate("Dialog", "Successful"))
        self.comboBox_Attempt02.setItemText(2, _translate("Dialog", "Failed"))
        self.label_Attempt03.setText(_translate("Dialog", "Attempt #3:"))
        self.comboBox_Attempt03.setItemText(0, _translate("Dialog", "Unknown"))
        self.comboBox_Attempt03.setItemText(1, _translate("Dialog", "Successful"))
        self.comboBox_Attempt03.setItemText(2, _translate("Dialog", "Failed"))
        self.label_Attempt04.setText(_translate("Dialog", "Attempt # 4:"))
        self.comboBox_Attempt04.setItemText(0, _translate("Dialog", "Unknown"))
        self.comboBox_Attempt04.setItemText(1, _translate("Dialog", "Successful"))
        self.comboBox_Attempt04.setItemText(2, _translate("Dialog", "Failed"))
        self.label_Attempt05.setText(_translate("Dialog", "Attempt #5:"))
        self.comboBox_Attempt05.setItemText(0, _translate("Dialog", "Unknown"))
        self.comboBox_Attempt05.setItemText(1, _translate("Dialog", "Successful"))
        self.comboBox_Attempt05.setItemText(2, _translate("Dialog", "Failed"))
        self.label_Attempt06.setText(_translate("Dialog", "Attempt # 6:"))
        self.comboBox_Attempt06.setItemText(0, _translate("Dialog", "Unknown"))
        self.comboBox_Attempt06.setItemText(1, _translate("Dialog", "Successful"))
        self.comboBox_Attempt06.setItemText(2, _translate("Dialog", "Failed"))
        self.label_Attempt07.setText(_translate("Dialog", "Attempt # 7:"))
        self.comboBox_Attempt07.setItemText(0, _translate("Dialog", "Unknown"))
        self.comboBox_Attempt07.setItemText(1, _translate("Dialog", "Successful"))
        self.comboBox_Attempt07.setItemText(2, _translate("Dialog", "Failed"))
        self.label_Attempt08.setText(_translate("Dialog", "Attempt #8:"))
        self.comboBox_Attempt08.setItemText(0, _translate("Dialog", "Unknown"))
        self.comboBox_Attempt08.setItemText(1, _translate("Dialog", "Successful"))
        self.comboBox_Attempt08.setItemText(2, _translate("Dialog", "Failed"))
        self.label_Attempt09.setText(_translate("Dialog", "Attempt # 9:"))
        self.comboBox_Attempt09.setItemText(0, _translate("Dialog", "Unknown"))
        self.comboBox_Attempt09.setItemText(1, _translate("Dialog", "Successful"))
        self.comboBox_Attempt09.setItemText(2, _translate("Dialog", "Failed"))
        self.label_Attempt10.setText(_translate("Dialog", "Attempt #10:"))
        self.comboBox_Attempt10.setItemText(0, _translate("Dialog", "Unknown"))
        self.comboBox_Attempt10.setItemText(1, _translate("Dialog", "Successful"))
        self.comboBox_Attempt10.setItemText(2, _translate("Dialog", "Failed"))
        self.label_Attempt11.setText(_translate("Dialog", "Attempt # 11:           (If Necessary)"))
        self.comboBox_Attempt11.setItemText(0, _translate("Dialog", "Unknown"))
        self.comboBox_Attempt11.setItemText(1, _translate("Dialog", "Successful"))
        self.comboBox_Attempt11.setItemText(2, _translate("Dialog", "Failed"))
        self.label_TotalAttempts_2.setText(_translate("Dialog", "Clutch Attempts:"))
        self.label_SuccessfulAttempts_2.setText(_translate("Dialog", "Successful Clutch Attempts:"))

